### PR TITLE
Added language system

### PR DESCRIPTION
**Pull request by 1461748123**
Added language system. Chinese translations as well.
Still have to work on API translations.
Also added location display on title bar.

### CODE REVIEW

**Comment by shiftcodeYT** [comment]
Why did you close it?

**Comment by 1461748123** [comment]
Sorry, got some wrong files uploaded :/ *forgot to erase my pass and account*

**Comment by shiftcodeYT** [comment]
It happens :D

**Comment by 1461748123** [comment]
now, done :D

**Pull request closed without merging**
